### ISSUE TITLE
Alle Spieler hören sich

### ISSUE THREAD

**Issue by xzessmedia** [Cryma/RealityVoice#13]
In der letzten Version war die Sprache distanzabhängig.
Jetzt hören sich alle Spieler gegenseitig.
Ist das so gedacht?

Kann man irgendwie mehr Channels erstellen? Also ich suche noch einen Punkt an dem ich die Messages filtern kann, zB. Spieler hört nur wenn string channel = "xyz"
Ich möchte gerne mehr darüber verstehen, das klappt am besten wenn man damit arbeitet :)
Möchte dann auch gerne aktiv hier mitarbeiten damit alle etwas davon haben.
Diese Informationen wären daher sehr hilfreich!
Vielen Dank für diese tolle Arbeit zur rechten Zeit!

**Comment by Cryma** [comment]
Der Fehler mit den Distanzen sollte jetzt behoben sein!

Zu den Channels: Möglich ist das auf jeden Fall, der Server müsste dann jeweils den Channel von dem Spieler mit den Voice-Daten mitschicken und der Client muss schauen, ob dieser mit dem eigenen übereinstimmt.

**Comment by xzessmedia** [comment]
Vielen Dank, kann geschlossen werden!
