### ISSUE TITLE
Secret Token

### ISSUE THREAD

**Issue by zenzcode** [Cryma/RealityVoice#15]
Wie bekomme ich den Token? Ich hab das nicht ganz verstanden. :/

**Comment by Cryma** [comment]
Der Token kann anhand des OnTokenGenerated Events abgegriffen werden. In der Beispiel-Ressource wird der Token in die Konsole geschrieben (siehe [hier](https://github.com/Cryma/RealityVoice/blob/master/Example/Resource/VoiceServer.cs#L29)).

Der Token dient zum Authentifizieren zwischen dem Nutzer und dem Server.
