### ISSUE TITLE
Server crashes after running build

### ISSUE THREAD

**Issue by xzessmedia** [Cryma/RealityVoice#5]
After building the server and copying the files to the server folder the server will crash:

Unbehandelte Ausnahme: System.MissingMethodException: Methode nicht gefunden: "Void Lidgren.Network.NetPeerConfiguration.set_MaxPlayers(Int32)".
   bei GrandTheftMultiplayer.Server.GameServer.?????????????????????????????????????????(NetPeerConfiguration , Int32 )
   bei GrandTheftMultiplayer.Server.GameServer..ctor(ServerSettings serverSettings)
   bei GrandTheftMultiplayer.Server.Program.Main(String[] args)

**Comment by Cryma** [comment]
@xzessmedia Does this happen when starting the example resource or while implementing it yourself? And according to the stack trace, it is likely GT-MP related and not from RealityVoice...

**Comment by xzessmedia** [comment]
oh nice, it was my own mistake, i didn't see the example.. now everything is clear and works.
issue can be closed now!

thanks for fast response
